### ISSUE TITLE
Improper article for numbers like 1.1

### ISSUE THREAD

**Issue by ferenci-tamas** [dmurdoch/magyarbookdown#1]
The package outputs `a 1.1` instead of `az 1.1`. The reason seems to be that `magyar_article` checks whether the number's length is divisible with 3, if it begins with 1. That makes perfect sense for numbers (`az 1` and `a 111` are the correct articles), but not for labels, because 1.1 is pronounced the same as 1, i.e. everything that comes after the first period is irrelevant from the pronunciation aspect (and thus from the article aspect).

**Comment by dmurdoch** [comment]
Thanks for the report.  Could you reinstall and give it another try now?  I fixed some bugs.

**Comment by ferenci-tamas** [comment]
I'm afraid you haven't uploaded it (at least Github still shows two commits, the last being 9 hours old).

**Comment by dmurdoch** [comment]
That's the one I was talking about.  If it doesn't fix the issue, could you attach a small sample document that I could try out?

**Comment by ferenci-tamas** [comment]
Sorry, I somehow, overlooked that it contains the fix! I checked, and it is perfect now, on my original document too. Thank you very much!
